function vertex = beamVertex(beam,nodes)
    for i = 1:beam.nbeam;
    vertex(i,:)     = [ nodes.x(beam.nodes2(i))-nodes.x(beam.nodes1(i))...
                        nodes.y(beam.nodes2(i))- nodes.y(beam.nodes1(i))...
                        nodes.z(beam.nodes2(i))-nodes.z(beam.nodes1(i))...
                        beam.disc];
    end
end