
function modelLcs = lcsModelFn(headNode,tMatrix)
GCS = [1 0 0; 0 1 0; 0 0 1];
Lcs = GCS*tMatrix(1:3,1:3);
Y = plot3 ( ...
    [headNode(1) headNode(1)+Lcs(2,1)],...
    [headNode(2) headNode(2)+Lcs(2,2)],...
    [headNode(3) headNode(3)+Lcs(2,3)],...
    'k','LineWidth',1,'Color', 'g');
Z = plot3 ( ...
    [headNode(1) headNode(1)+Lcs(3,1)],...
    [headNode(2) headNode(2)+Lcs(3,2)],...
    [headNode(3) headNode(3)+Lcs(3,3)],...
    'k','LineWidth',1,'Color', 'b');
X = plot3 ( ...
    [headNode(1) headNode(1)+Lcs(1,1)],...
    [headNode(2) headNode(2)+Lcs(1,2)],...
    [headNode(3) headNode(3)+Lcs(1,3)],...
    'k','LineWidth',1,'Color', 'r');
modelLcs = [X,Y,Z];