function passed = run_single_test(testNum)
% run_single_test  Run one 2D frame test and compare displacements/moments.
%
% USAGE:
%   passed = run_single_test(1)
%
% Tests 1 and 2: compared against analytical reference.
% Test 3:        compared against FEM reference (generated by generate_references).
%
% INPUTS:
%   testNum  - integer (1, 2, 3)
%
% OUTPUTS:
%   passed   - true if max relative error < tolerance
%
% (c) S. Glanc, 2026

TOL_PCT = 0.01;   % 0.01 % tolerance

testDir = fullfile(fileparts(mfilename('fullpath')), sprintf('Test %d', testNum));
srcDir  = fullfile(fileparts(fileparts(mfilename('fullpath'))), 'src');
addpath(srcDir);

% Load and run
run(fullfile(testDir, 'test_input.m'));
[displacements, endForces] = linearSolverFn(sections, nodes, 10, kinematic, beams, loads);

% Load reference
refFile = fullfile(testDir, 'reference.mat');
if ~isfile(refFile)
    error('Reference not found: %s\nRun generate_references.m first.', refFile);
end
ref = load(refFile);

% Compare: use uz displacement at free/loaded nodes and end moments
d_fem = full(displacements.global);
d_ref = ref.d_ref(:);

% Normalise by max absolute value to get relative error
denom   = max(abs(d_ref), 1e-12);
err_pct = abs(d_fem - d_ref) ./ denom * 100;
maxErr  = max(err_pct);
passed  = maxErr < TOL_PCT;

fprintf('Test %d: ', testNum);
if passed
    fprintf('PASSED  (max err = %.4g %%)\n', maxErr);
else
    fprintf('FAILED  (max err = %.4g %%)\n', maxErr);
end
end
